//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp_Web.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BankApp_Web.Translations.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Rekeningen {
            get {
                return ResourceManager.GetString("Rekeningen", resourceCulture);
            }
        }
        
        public static string Transacties {
            get {
                return ResourceManager.GetString("Transacties", resourceCulture);
            }
        }
        
        public static string Wachtende_Transacties {
            get {
                return ResourceManager.GetString("Wachtende Transacties", resourceCulture);
            }
        }
        
        public static string Gebruikersbeheer {
            get {
                return ResourceManager.GetString("Gebruikersbeheer", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string Hallo {
            get {
                return ResourceManager.GetString("Hallo", resourceCulture);
            }
        }
        
        public static string Uitloggen {
            get {
                return ResourceManager.GetString("Uitloggen", resourceCulture);
            }
        }
        
        public static string Registreren {
            get {
                return ResourceManager.GetString("Registreren", resourceCulture);
            }
        }
        
        public static string Inloggen {
            get {
                return ResourceManager.GetString("Inloggen", resourceCulture);
            }
        }
    }
}
